services:
  migrator:
    image: ghcr.io/maxnumerique/velo-repar-lyon:latest
    container_name: velo-repar-migrator
    command: npx prisma db push --accept-data-loss
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  app:
    image: ghcr.io/maxnumerique/velo-repar-lyon:latest
    container_name: velo-repar-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  db:
    image: postgis/postgis:15-3.3
    container_name: velo-repar-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-velo_admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-velo_pass}
      - POSTGRES_DB=${DB_NAME:-velodupelo}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-velo_admin} -d ${DB_NAME:-velodupelo}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
