services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
        - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
        - NEXT_PUBLIC_MAPTILER_KEY=${NEXT_PUBLIC_MAPTILER_KEY}
        - NEXT_PUBLIC_GOOGLE_MAPS_API=${NEXT_PUBLIC_GOOGLE_MAPS_API}
        - NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}
    container_name: velo-repar-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-velo_admin}:${DB_PASSWORD:-velo_pass}@db:5432/${DB_NAME:-velodupelo}?schema=public
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:15-3.3
    container_name: velo-repar-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-velo_admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-velo_pass}
      - POSTGRES_DB=${DB_NAME:-velodupelo}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-velo_admin} -d ${DB_NAME:-velodupelo}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: velo-repar-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
